/**
 * Converts snarkjs proof.json + verification_key.json + public.json
 * into Rust byte-array literals for the E2E test in groth16-verifier.
 *
 * Output is printed to stdout — pipe it into a file or paste into the test.
 *
 * Usage:
 *   node scripts/proof_to_rust.js proof.json public.json verification_key.json
 */

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Encoding helpers
// ---------------------------------------------------------------------------

function decToBE32(decStr) {
    let n = BigInt(decStr);
    const buf = new Uint8Array(32);
    for (let i = 31; i >= 0; i--) {
        buf[i] = Number(n & 0xffn);
        n >>= 8n;
    }
    return buf;
}

/** G1 point [xDec, yDec, "1"] → 64-byte big-endian buffer */
function g1ToBytes(p) {
    const x = decToBE32(p[0]);
    const y = decToBE32(p[1]);
    const out = new Uint8Array(64);
    out.set(x, 0);
    out.set(y, 32);
    return out;
}

/**
 * G2 point [[x0Dec, x1Dec], [y0Dec, y1Dec], ["0","1"]] → 128-byte buffer
 * soroban-sdk v25 / EIP-197 encoding: X.c1 || X.c0 || Y.c1 || Y.c0
 * (imaginary part first)
 *
 * snarkjs stores G2 as [[x_re, x_im], [y_re, y_im]] (real before imaginary)
 * We swap to imaginary-first for the contract.
 */
function g2ToBytes(p) {
    const xRe = decToBE32(p[0][0]);  // X.c0
    const xIm = decToBE32(p[0][1]);  // X.c1
    const yRe = decToBE32(p[1][0]);  // Y.c0
    const yIm = decToBE32(p[1][1]);  // Y.c1
    const out = new Uint8Array(128);
    out.set(xIm, 0);   // X.c1 first
    out.set(xRe, 32);  // X.c0 second
    out.set(yIm, 64);  // Y.c1 third
    out.set(yRe, 96);  // Y.c0 fourth
    return out;
}

function bytesToRustArray(name, bytes, type = null) {
    const len = bytes.length;
    const typeStr = type || `[u8; ${len}]`;
    const hex = Array.from(bytes)
        .map((b, i) => {
            const s = "0x" + b.toString(16).padStart(2, "0");
            return (i + 1) % 16 === 0 ? s + ",\n        " : s + ", ";
        })
        .join("")
        .trimEnd()
        .replace(/,\s*$/, "");
    return `const ${name}: ${typeStr} = [\n        ${hex}\n    ];`;
}

// ---------------------------------------------------------------------------
// VK serialization
// ---------------------------------------------------------------------------

function vkToBytes(vk) {
    const alpha = g1ToBytes(vk.vk_alpha_1);
    const beta  = g2ToBytes(vk.vk_beta_2);
    const gamma = g2ToBytes(vk.vk_gamma_2);
    const delta = g2ToBytes(vk.vk_delta_2);

    const numIc = vk.IC.length;
    const numIcBuf = new Uint8Array(4);
    numIcBuf[0] = (numIc >> 24) & 0xff;
    numIcBuf[1] = (numIc >> 16) & 0xff;
    numIcBuf[2] = (numIc >>  8) & 0xff;
    numIcBuf[3] =  numIc        & 0xff;

    const icBytes = vk.IC.map(p => g1ToBytes(p));

    const total = 64 + 128 + 128 + 128 + 4 + numIc * 64;
    const out = new Uint8Array(total);
    let offset = 0;
    out.set(alpha,    offset); offset += 64;
    out.set(beta,     offset); offset += 128;
    out.set(gamma,    offset); offset += 128;
    out.set(delta,    offset); offset += 128;
    out.set(numIcBuf, offset); offset += 4;
    for (const ic of icBytes) {
        out.set(ic, offset); offset += 64;
    }
    return out;
}

// ---------------------------------------------------------------------------
// Proof serialization
// ---------------------------------------------------------------------------

function proofToBytes(proof) {
    const a = g1ToBytes(proof.pi_a);
    const b = g2ToBytes(proof.pi_b);
    const c = g1ToBytes(proof.pi_c);
    const out = new Uint8Array(256);
    out.set(a, 0);
    out.set(b, 64);
    out.set(c, 192);
    return out;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const [,, proofPath, publicPath, vkPath] = process.argv;

if (!proofPath || !publicPath || !vkPath) {
    console.error("Usage: node proof_to_rust.js proof.json public.json verification_key.json");
    process.exit(1);
}

const proof  = JSON.parse(fs.readFileSync(proofPath,  "utf8"));
const pub    = JSON.parse(fs.readFileSync(publicPath,  "utf8")); // array of decimal strings
const vk     = JSON.parse(fs.readFileSync(vkPath,     "utf8"));

const proofBytes = proofToBytes(proof);
const vkBytes    = vkToBytes(vk);

// Public inputs as 32-byte big-endian each
const pubInputsBytes = pub.map((v, i) => ({ name: `PUB_INPUT_${i}`, bytes: decToBE32(v) }));

// Print Rust output
console.log("// Auto-generated by scripts/proof_to_rust.js — DO NOT EDIT BY HAND");
console.log("// Source: proof.json + public.json + verification_key.json");
console.log("// Circuit: withdraw.circom (Withdraw(depth=20), 5 public inputs)");
console.log("");
console.log(`// Proof bytes: ${proofBytes.length} bytes (A:64 B:128 C:64)`);
console.log(bytesToRustArray("PROOF_BYTES", proofBytes));
console.log("");
console.log(`// VK bytes: ${vkBytes.length} bytes (num_ic = ${vk.IC.length}, ${vk.IC.length - 1} public inputs)`);
console.log(bytesToRustArray("VK_BYTES", vkBytes));
console.log("");
console.log("// Public inputs (5 x 32 bytes, big-endian BN254 scalar field elements)");
console.log(`// Order: [poolMerkleRoot, aspMerkleRoot, nullifierHash, recipient, amountPub]`);
for (const { name, bytes } of pubInputsBytes) {
    console.log(bytesToRustArray(name, bytes));
}
console.log("");
console.log("// Decoded public values (for documentation):");
pub.forEach((v, i) => {
    const labels = ["poolMerkleRoot", "aspMerkleRoot", "nullifierHash", "recipient", "amountPub"];
    console.log(`// [${i}] ${labels[i] || "?"} = ${v}`);
});